### ISSUE TITLE
Cannot load such file "bigdecimal/util"

### ISSUE THREAD

**Issue by soukicz** [kaizenplatform/fluent-plugin-bigquery#106]
I am getting new error after activesupport update (#103)

```
~ $ fluentd -c /home/fluent/fluentd.conf -p /fluentd/plugins
2016-12-19 11:10:41 +0000 [info]: reading config file path="/home/fluent/fluentd.conf"
2016-12-19 11:10:41 +0000 [info]: starting fluentd-0.12.31
2016-12-19 11:10:42 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2016-12-19 11:10:42 +0000 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-12-19 11:10:42 +0000 [info]: gem 'fluent-plugin-bigquery' version '0.3.4'
2016-12-19 11:10:42 +0000 [info]: gem 'fluent-plugin-buffer-lightening' version '0.0.2'
2016-12-19 11:10:42 +0000 [info]: gem 'fluentd' version '0.12.31'
2016-12-19 11:10:42 +0000 [info]: adding match pattern="nginx.shop-access" type="bigquery"
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bigdecimal/util (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/object/json.rb:4:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/fluent/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-bigquery-0.3.4/lib/fluent/plugin/out_bigquery.rb:167:in `initialize'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/plugin.rb:132:in `new'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/plugin.rb:132:in `new_impl'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/plugin.rb:59:in `new_output'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:131:in `add_match'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:64:in `block in configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:57:in `each'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:57:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/root_agent.rb:86:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/engine.rb:129:in `configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/engine.rb:103:in `run_configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:489:in `run_configure'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:160:in `block in start'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:366:in `main_process'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:339:in `block in supervise'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:338:in `fork'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:338:in `supervise'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:156:in `start'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.31/bin/fluentd:5:in `<top (required)>'
        from /usr/bin/fluentd:23:in `load'
        from /usr/bin/fluentd:23:in `<main>'
2016-12-19 11:10:42 +0000 [info]: process finished code=256
2016-12-19 11:10:42 +0000 [warn]: process died within 1 second. exit.
```

**Comment by joker1007** [comment]
bigdecimal is embedded gem.
And so, If you use normal ruby environment, bigdecimal gem is installed initially.
Would you tell me more information about your environment ?

**Comment by soukicz** [comment]
I ma using oficial fluentd docker image: https://github.com/fluent/fluentd-docker-image/blob/master/Dockerfile.sample

It is working after installing bigdecimal gem:
```
FROM fluent/fluentd:v0.12-latest
WORKDIR /home/fluent
ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH

USER root
RUN apk --no-cache add sudo build-base ruby-dev && \
    sudo -u fluent gem install fluent-plugin-bigquery bigdecimal && \
    rm -rf /home/fluent/.gem/ruby/2.3.0/cache/*.gem && sudo -u fluent gem sources -c && \
    apk del sudo build-base ruby-dev

COPY google.json /home/fluent/google.json
COPY fluentd.conf /home/fluent/fluentd.conf

USER fluent
CMD exec fluentd -c /home/fluent/fluentd.conf -p /fluentd/plugins $FLUENTD_OPT
```

**Comment by joker1007** [comment]
I see. Thanks!!

Official fluentd docker image omits some embedded gems in order to shrink image size.
I guess that bigdecimal gem is omitted too.
Could you add `RUN gem install bigdecimal` or `RUN fluent-gem install bigdecimal` to your Dockerfile?
I think that it solves this probrem.

**Comment by soukicz** [comment]
It is already in Dockerfile posted above and it works perfectly :)
I don't realy know how ruby works, but does it make sense to add bigdecimal as dependency in bigquery plugin?

**Comment by joker1007** [comment]
Almost rubygems don't have dependency for embedded gems.
I think that fluentd docker image is irregular.
I will notice this issue to maintainer of fluentd docker image.
Thanks!!

**Comment by asmsuechan** [comment]
@joker1007 I also hit this problem.
According to [this](https://github.com/fluent/fluentd-docker-image/pull/31), ruby-bigdecimal is unlikely included fluentd docker image for now. What do you think how to solve it?

**Comment by joker1007** [comment]
https://github.com/kaizenplatform/fluent-plugin-bigquery/commit/18ded291c58734a0b6c1235d09ce63f505aec975
