### ISSUE TITLE
Weird error with "Google::Apis::TransmissionError"

### ISSUE THREAD

**Issue by edwardchuang** [kaizenplatform/fluent-plugin-bigquery#116]
My fluentd with bigquery plugin got the error message below and it seems lead high CPU usage, anyone have any clue on this ?

```
2017-03-16 15:31:40 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2017-03-16 15:31:02 +0800 error_class="Google::Apis::TransmissionError" error="SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A" plugin_id="object:3f847a2f9f20"
2017-03-16 15:31:41 +0800 [warn]: retry succeeded. plugin_id="object:3f847a2f9f20"
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.8.2.4/lib/httpclient/ssl_socket.rb:46:in `connect'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.8.2.4/lib/httpclient/ssl_socket.rb:46:in `ssl_connect'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.8.2.4/lib/httpclient/ssl_socket.rb:24:in `create_socket'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:746:in `block in connect'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:90:in `block in timeout'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:100:in `call'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:100:in `timeout'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:742:in `connect'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:504:in `query'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:174:in `query'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1240:in `do_get_block'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1017:in `block in do_request'
2017-03-16 15:31:43 +0800 [warn]: buffer flush took longer time than slow_flush_log_threshold: plugin_id="object:3f847994ec50" elapsed_time=45.6442592 slow_flush_log_threshold=40.0
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1131:in `protect_keep_alive_disconnected'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1012:in `do_request'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:854:in `request'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.28/lib/google/apis/core/http_client_adapter.rb:17:in `block in call'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/hurley-0.2/lib/hurley/client.rb:252:in `initialize'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.28/lib/google/apis/core/http_client_adapter.rb:16:in `new'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.28/lib/google/apis/core/http_client_adapter.rb:16:in `call'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/hurley-0.2/lib/hurley/client.rb:122:in `call_with_redirects'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/hurley-0.2/lib/hurley/client.rb:89:in `call'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/hurley-0.2/lib/hurley/client.rb:71:in `post'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.28/lib/google/apis/core/http_command.rb:272:in `execute_once'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.28/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.28/lib/google/apis/core/http_command.rb:104:in `block in execute'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.28/lib/google/apis/core/http_command.rb:96:in `execute'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.28/lib/google/apis/core/base_service.rb:353:in `execute_or_queue_command'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.28/generated/google/apis/bigquery_v2/service.rb:664:in `insert_all_table_data'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.4.0/lib/fluent/plugin/bigquery/writer.rb:94:in `insert_rows'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.4.0/lib/fluent/plugin/out_bigquery.rb:426:in `insert'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.4.0/lib/fluent/plugin/out_bigquery.rb:421:in `block in _write'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.4.0/lib/fluent/plugin/out_bigquery.rb:420:in `each'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.4.0/lib/fluent/plugin/out_bigquery.rb:420:in `_write'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.4.0/lib/fluent/plugin/out_bigquery.rb:352:in `write'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:354:in `write_chunk'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:333:in `pop'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.33/lib/fluent/output.rb:342:in `try_flush'
  2017-03-16 15:31:40 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.33/lib/fluent/output.rb:149:in `run'
```

**Comment by joker1007** [comment]
2nd warn `slow_flush_log_threshold` is fluentd feature. the threshold is configurable.
Although you use "Streaming Insert" method, I seems to be very slow flushing.
Maybe, cause of this is the 1st warn message, but I don't know detail, sorry.

Bigquery API becomes often unstable. Because of this, connection error often occurs.
I have seen such warning messages. but the messages has not leaded high CPU usage.
