### ISSUE TITLE
rake test fails

### ISSUE THREAD

**Issue by fujio0000** [kaizenplatform/fluent-plugin-bigquery#162]
## Environments
ruby-version : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

## Configuration
no

## Expected Behavior
- Test succeeds

## Actual Behavior
- `rake test` fails

## Log (if you have)
```
E
============================================================================================================================================================================
     214:     stub_writer(stub_auth: false) do |writer|
     215:       mock.proxy(writer).get_auth_from_application_default { stub! }
     216:     end
  => 217:     assert driver.instance.writer.client.is_a?(Google::Apis::BigqueryV2::BigqueryService)
     218:   end
     219:
     220:   def test_format
/home/vagrant/fluent-plugin-bigquery/test/plugin/test_out_bigquery_base.rb:217:in `test_configure_auth_application_default'
/home/vagrant/fluent-plugin-bigquery/lib/fluent/plugin/bigquery/writer.rb:13:in `client'
/home/vagrant/fluent-plugin-bigquery/lib/fluent/plugin/bigquery/writer.rb:13:in `tap'
/home/vagrant/fluent-plugin-bigquery/lib/fluent/plugin/bigquery/writer.rb:14:in `block in client'
/home/vagrant/fluent-plugin-bigquery/lib/fluent/plugin/bigquery/writer.rb:252:in `get_auth'
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rr-1.2.1/lib/rr/injections/double_injection.rb:148:in `get_auth_from_application_default'
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rr-1.2.1/lib/rr/injections/double_injection.rb:40:in `dispatch_method'
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rr-1.2.1/lib/rr/injections/double_injection.rb:183:in `dispatch_method'
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rr-1.2.1/lib/rr/method_dispatches/method_dispatch.rb:16:in `call'
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rr-1.2.1/lib/rr/method_dispatches/method_dispatch.rb:41:in `call_implementation'
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rr-1.2.1/lib/rr/method_dispatches/method_dispatch.rb:30:in `call_original_method'
/home/vagrant/fluent-plugin-bigquery/lib/fluent/plugin/bigquery/writer.rb:294:in `get_auth_from_application_default'
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/googleauth-0.6.2/lib/googleauth/application_default.rb:61:in `get_application_default'
Error: test_configure_auth_application_default(BigQueryBaseOutputTest):
  RuntimeError: Could not load the default credentials. Browse to
  https://developers.google.com/accounts/docs/application-default-credentials
  for more information
============================================================================================================================================================================
```

**Comment by fujio0000** [comment]
I executed bundle update but it did not work.

Execution will result in an error of issue
```
$  git clone https://github.com/kaizenplatform/fluent-plugin-bigquery.git
$  cd fluent-plugin-bigquery/
$  bundle install
$  bundle exec rake test
```
No matter how many times this procedure is executed, an error will occur.
Do you need additional settings such as environment variables?

**Comment by joker1007** [comment]
I tried to clone this repository and execute `bundle install` and run test.
But I cannot regenerate error. :disappointed: 

You seem to use old ruby (2.2.x). That is already end of life.
td-agent3 uses ruby-2.4.x. And this plugins supports fluentd-1.0.x or later.
Please update ruby version to 2.4.x or later.
