### ISSUE TITLE
Big query no longer inserting: Errno::EPIPE

### ISSUE THREAD

**Issue by smcavoy-b** [kaizenplatform/fluent-plugin-bigquery#42]
Hello,
I have started to see an error with the bigquery plugin. I get a Errno::EPIPE and no further details.
Is there anything that can be done to make the logging more verbose? I am already running td-agent with -vvv 
Thanks,

Sean 

stacktrace:
```
2015-06-09 09:36:17 +0000 [warn]: fluent/output.rb:354:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2015-06-09 09:36:11 +0000 error_class="Errno::EPIPE" error="Broken pipe" plugin_id="redir-vis"
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:326:in `syswrite'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:326:in `do_write'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:344:in `write'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/protocol.rb:211:in `write0'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/protocol.rb:185:in `block in write'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/protocol.rb:202:in `writing'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/protocol.rb:184:in `write'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http/generic_request.rb:184:in `send_request_with_body'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http/generic_request.rb:130:in `exec'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:1406:in `block in transport_request'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:1378:in `request'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:1371:in `block in request'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:853:in `start'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:1369:in `request'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.6/lib/google/api_client/request.rb:163:in `send'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:648:in `block (2 levels) in execute!'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:645:in `block in execute!'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:636:in `execute!'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:679:in `execute'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.2.8/lib/fluent/plugin/out_bigquery.rb:285:in `insert'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.2.8/lib/fluent/plugin/out_bigquery.rb:346:in `write'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:325:in `write_chunk'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:304:in `pop'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:321:in `try_flush'
  2015-06-09 09:36:17 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:140:in `run'
```

**Comment by smcavoy-b** [comment]
After some investigation by a team member it was discovered the problem is the chunk size.
When writing to BigQuery the chunk size set in FluentD which causes a problem if it exceeds the maximum size of chunk allowed by BigQuery.

The fix is to set the chunk size for the fluentd side to be less than the max of BigQuery which is 10MiB

Closing
