### ISSUE TITLE
active_support/json LoadError in v0.2.15

### ISSUE THREAD

**Issue by bungoume** [kaizenplatform/fluent-plugin-bigquery#64]
I have encountered this error in v0.2.15 .
This plugin requires active_support(rails)?

```
06:42:54 system      | sending SIGTERM to all processes
06:42:54 dockergen.1 | terminated by SIGTERM
06:42:54 fluentd.1   | exited with code 0
06:42:54             | 2016-03-01 06:42:54 +0000 [info]: shutting down fluentd
06:42:54             | 2016-03-01 06:42:54 +0000 [info]: shutting down input type="forward" plugin_id="object:2aca4b870cb8"
06:42:54             | 2016-03-01 06:42:54 +0000 [info]: shutting down input type="forward" plugin_id="object:2aca4b871960"
06:42:54             | /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_support/json (LoadError)
06:42:54             | 	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
06:42:54             | 	from /usr/local/bundle/gems/fluent-plugin-bigquery-0.2.15/lib/fluent/plugin/out_bigquery.rb:137:in `initialize'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin.rb:128:in `new'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin.rb:128:in `new_impl'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin.rb:57:in `new_output'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin/out_copy.rb:42:in `block in configure'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin/out_copy.rb:35:in `each'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin/out_copy.rb:35:in `configure'
06:42:54             | 	from /usr/local/bundle/gems/fluent-plugin-forest-0.3.0/lib/fluent/plugin/out_forest.rb:132:in `block in plant'
06:42:54             | 	from /usr/local/bundle/gems/fluent-plugin-forest-0.3.0/lib/fluent/plugin/out_forest.rb:128:in `synchronize'
06:42:54             | 	from /usr/local/bundle/gems/fluent-plugin-forest-0.3.0/lib/fluent/plugin/out_forest.rb:128:in `plant'
06:42:54             | 	from /usr/local/bundle/gems/fluent-plugin-forest-0.3.0/lib/fluent/plugin/out_forest.rb:168:in `emit'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/event_router.rb:88:in `emit_stream'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin/in_forward.rb:155:in `on_message'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin/in_forward.rb:276:in `call'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin/in_forward.rb:276:in `block in on_read_msgpack'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin/in_forward.rb:275:in `feed_each'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin/in_forward.rb:275:in `on_read_msgpack'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin/in_forward.rb:261:in `call'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin/in_forward.rb:261:in `on_read'
06:42:54             | 	from /usr/local/bundle/gems/cool.io-1.4.3/lib/cool.io/io.rb:123:in `on_readable'
06:42:54             | 	from /usr/local/bundle/gems/cool.io-1.4.3/lib/cool.io/io.rb:186:in `on_readable'
06:42:54             | 	from /usr/local/bundle/gems/cool.io-1.4.3/lib/cool.io/loop.rb:88:in `run_once'
06:42:54             | 	from /usr/local/bundle/gems/cool.io-1.4.3/lib/cool.io/loop.rb:88:in `run'
06:42:54             | 	from /usr/local/bundle/gems/fluentd-0.12.20/lib/fluent/plugin/in_forward.rb:98:in `run'
06:42:54             | 2016-03-01 06:42:54 +0000 [info]: process finished code=256
```

**Comment by bungoume** [comment]
It seems to be fixed at https://github.com/kaizenplatform/fluent-plugin-bigquery/commit/2fe1a813207e3c9d792a2da00ee46b1f9cd74ed7 and v0.2.16.

thank you!
