### ISSUE TITLE
Plugin with PHP input?

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [kaizenplatform/fluent-plugin-bigquery#76]
I am trying to test this fluentd plugin with the php input however I get the following problem:

```
2016-06-03 12:06:06 -0400 [warn]: temporarily failed to flush the buffer. next_retry=2016-06-03 12:06:07 -0400 error_class="MultiJson::ParseError" error="invalid comment format at line 1, column 1 [parse.c:96]" plugi$
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib/multi_json/adapters/oj.rb:15:in `load'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib/multi_json/adapters/oj.rb:15:in `load'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib/multi_json/adapter.rb:21:in `load'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib/multi_json.rb:119:in `load'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:75:in `read_json_key'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:59:in `make_creds'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.2.16/lib/fluent/plugin/out_bigquery.rb:272:in `client'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.2.16/lib/fluent/plugin/out_bigquery.rb:419:in `insert'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.2.16/lib/fluent/plugin/out_bigquery.rb:414:in `block in _write'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.2.16/lib/fluent/plugin/out_bigquery.rb:413:in `each'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.2.16/lib/fluent/plugin/out_bigquery.rb:413:in `_write'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-bigquery-0.2.16/lib/fluent/plugin/out_bigquery.rb:366:in `write'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/buffer.rb:345:in `write_chunk'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/buffer.rb:324:in `pop'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/output.rb:329:in `try_flush'
  2016-06-03 12:06:06 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/output.rb:140:in `run'
```

The data im sending does have some json encoded data (inside the json) as such:

```
$array = [
 'one'=>'{"something": [1,2,3,4]}',
 'two'=>2
];
```

Any insight on what might cause this issue?

**Comment by yuya-takeyama** [comment]
@Ewan-GrandSlam 
Your error seems to be raised from here.
https://github.com/kaizenplatform/fluent-plugin-bigquery/blob/2e04917bd9d8f12581d9b35010acf3cf669a5c9b/lib/fluent/plugin/out_bigquery.rb#L272

It's configuration phase of the plugin.
So the record sent from PHP is not matter.

Is the `json_key` is valid JSON or readable JSON file to `td-agent`?

Maybe this is related.
https://github.com/kaizenplatform/fluent-plugin-bigquery/pull/89
